import React from "react";
import { StyleSheet } from "react-native";

const color = {
  primaryColor: "#252644",
  formlabel: "#757578",
  orange: "#DD5B2C",
  white: "#fff",
  secondaryColor: "#00DE9D",
  green: "#2ED96C",
  red: "#E12B2B",
};

export const styles = StyleSheet.create({
  // splash
  splashcover: {
    width: "100%",
    height: "100%",
    backgroundColor: "#252644",
    position: "relative",
  },
  splashcontent: {
    position: "absolute",
    width: "100%",
    top: "30%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  splashimage: {
    width: 150,
    height: 150,
  },
  splashtext: {
    color: "#fff",
    fontSize: 25,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  // signin
  sigincover: {
    width: "100%",
    height: "auto",
  },
  siginimagecover: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    marginTop: 80,
  },
  siginimage: {
    width: 150,
    height: 150,
  },
  sigindesc: {
    marginTop: 35,
    paddingHorizontal: 10,
  },
  sigintitle: {
    fontSize: 25,
    marginBottom: 3,
    fontWeight: "bold",
    color: color.primaryColor,
  },
  sigincaption: {
    color: color.primaryColor,
    fontSize: 16,
    fontWeight: "300",
    letterSpacing: 1,
    marginBottom: 15,
  },
  formgroup: {
    width: "100%",
    marginTop: 15,
  },
  siginlabel: {
    color: color.formlabel,
    fontSize: 14,
    // marginBottom: 15,
  },
  sigininputcover: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    height: 45,
    borderBottomColor: "#b1b1b1",
    borderBottomWidth: 1,
  },
  signinicon: {
    width: "10%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  signinput: {
    width: "80%",
    paddingHorizontal: 10,
  },
  eye: {
    width: "10%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  forgotpassword: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    marginVertical: 10,
  },
  forgotpasswordtext: {
    color: color.orange,
  },
  signinbtn: {
    backgroundColor: color.primaryColor,
    height: 50,
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  signinbtntext: {
    color: color.white,
    fontSize: 16,
    fontWeight: "bold",
  },
  accounttextcover: {
    paddingHorizontal: 15,
    marginTop: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  accounttext: {
    marginTop: 5,
  },
  accountauthbtn: {
    color: color.secondaryColor,
    textDecorationLine: "underline",
    fontWeight: "500",
  },
  // signup
  signuptopbtn: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    paddingRight: 10,
    marginTop: 30,
  },
  signuptoptext: {
    color: color.primaryColor,
    paddingLeft: 6,
    fontSize: 18,
  },
  signupcover: {
    paddingHorizontal: 10,
  },
  signupimageCover: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  signupimage: {
    width: 100,
    height: 100,
  },
  // home
  hometopcover: {
    backgroundColor: color.primaryColor,
    paddingHorizontal: 10,
    paddingTop: 50,
  },
  hometop: {
    width: "100%",
    height: 150,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    height: 50,
    marginBottom: 10,
    // borderWidth: 1,
    // borderColor: "#fff",
  },
  hometopleft: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    shadowColor: "#eee",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 3,
    elevation: 2,
  },
  homeimage: {
    width: 30,
    height: 30,
    borderRadius: 15,
  },
  homeusername: {
    color: color.white,
    fontSize: 16,
  },
  hometopright: {
    width: 30,
    height: 30,
    borderRadius: 15,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: color.secondaryColor,
    shadowColor: "#eee",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 3,
    elevation: 2,
  },
  homebottom: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginTop: 5,
    marginBottom: 50,
  },
  homeaccountcover: {},
  homeaccount: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 2,
  },
  homeaccountbalance: {
    color: color.white,
    fontSize: 22,
    fontWeight: "500",
  },
  homecurrencyview: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  homeaccounttext: {
    color: color.white,
    fontSize: 13,
    fontWeight: "400",
  },
  homecurrencyview: {
    width: 55,
    height: 30,
    borderRadius: 3,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: color.secondaryColor,
    shadowColor: "#eee",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 3,
    elevation: 2,
  },
  homewallets: {
    width: "100%",
    backgroundColor: color.white,
    height: "100%",
    marginTop: -40,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    padding: 15,
  },
  hometokentitle: {
    color: color.primaryColor,
    fontSize: 15,
    fontWeight: "bold",
    marginBottom: 10,
    marginTop: 15,
  },
  homesearch: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#eee",
    paddingHorizontal: 10,
    borderRadius: 9,
    backgroundColor: color.white,
  },
  hometokeninput: {
    height: 40,
    width: "90%",
  },
  homesearchicon: {
    width: 30,
    height: 30,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  tokencover: {
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 15,
  },
  tokenleft: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
  },
  tokenimagecover: {
    width: 40,
    height: 40,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    // backgroundColor: "#E2E3FE",
    borderRadius: 20,
  },
  tokenimage: {
    width: 40,
    height: 40,
  },
  tokeninfo: {
    display: "flex",
    justifyContent: "flex-end",
    marginLeft: 5,
  },
  tokenname: {
    color: "#3B5A7C",
    fontWeight: "bold",
    fontSize: 15,
  },
  tokenshortname: {
    color: "#ccc",
    fontSize: 14,
    textTransform: "uppercase",
  },
  tokenright: {
    width: "auto",
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-end",
  },
  tokenvolume: {
    color: color.green,
    marginRight: 15,
  },
  tokenpriceaction: {
    display: "flex",
    alignItems: "flex-end",
  },
  tokenprice: {
    color: "#3B5A7C",
    fontSize: 15,
    fontWeight: "bold",
    marginBottom: 7,
  },
  tokenequivalent: {
    color: "#3B5A7C",
  },
  chart: {
    width: "100%",
    height: "100%",
    backgroundColor: "#fff",
  },
  chartcover: {
    width: "100%",
    height: 500,
    backgroundColor: "#252644",
  },
  chartNav: {
    marginTop: 30,
    width: 57,
    height: 40,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
  },
  chartnavtext: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "300",
  },
  chartpair: {
    display: "flex",
    alignItems: "center",
  },
  chartpairtext: {
    color: "#d6ccff",
    textTransform: "uppercase",
    fontSize: 18,
    fontWeight: "500",
  },
  pairprice: {
    color: "#cbcbd4",
    marginTop: 30,
    marginBottom: 3,
    fontSize: 30,
  },
  pairpercentage: {
    fontSize: 20,
  },
  // profile
  profilecover: {
    padding: 10,
    width: "100%",
    height: "150%",
    backgroundColor: color.primaryColor,
  },
  profilenav: {
    display: "flex",
    alignItems: "flex-end",
  },
  profilenavtext: {
    color: color.primaryColor,
    fontSize: 17,
  },
  profiletopcover: {
    borderWidth: 1,
    display: "flex",
    alignItems: "center",
    backgroundColor: color.white,
    borderRadius: 10,
    paddingVertical: 10,
    marginBottom: 30,
  },
  profilepicture: {
    width: 70,
    height: 70,
    borderRadius: 35,
  },
  profilename: {
    fontWeight: "bold",
    color: color.primaryColor,
    fontSize: 15,
    marginTop: 5,
  },
  profileemail: {
    fontSize: 14,
    fontWeight: "300",
    color: color.primaryColor,
    textAlign: "center",
    marginTop: 2,
  },
  profilepid: {
    fontSize: 14,
    color: color.primaryColor,
    textAlign: "center",
    marginTop: 7,
  },
  profilesection: {
    backgroundColor: "#fff",
    borderRadius: 10,
    width: "100%",
    paddingHorizontal: 5,
    paddingVertical: 10,
    marginBottom: 15,
  },
  profilesectionlist: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 5,
    paddingBottom: 5,
  },
  profilesectionicon: {
    width: 25,
    height: 25,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 3,
  },
  profileleftcontent: {
    marginVertical: 5,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  profilesectiontitle: {
    color: color.primaryColor,
    fontWeight: "500",
    fontSize: 15,
    marginLeft: 10,
  },
  marketbtncover: {
    marginTop: 20,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
  },
  marketbtn: {
    width: 100,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: 35,
    borderRadius: 5,
  },
  marketbtntext: {
    color: color.white,
    fontSize: 16,
  },
  ordertitle: {
    marginTop: 10,
    fontSize: 18,
    color: color.primaryColor,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 8,
  },
  ordertop: {
    width: "100%",
    height: "auto",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopColor: "#ccc",
    borderTopWidth: 1,
    borderBottomColor: "#ccc",
    borderBottomWidth: 1,
    paddingHorizontal: 7,
  },
  orderaction: {
    width: "50%",
  },
  orderactiontext: {
    fontSize: 16,
    fontWeight: "bold",
    color: color.primaryColor,
    paddingVertical: 10,
  },
  orderbooktitle: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  orderpricevalue: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    height: "auto",
  },
  ordercolcover: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
  },
  ordercol: {
    paddingVertical: 3,
    width: "50%",
    paddingHorizontal: 7,
  },
  ordervaluecover: {
    height: "auto",
    width: "100%",
  },
  ordercoltext: {
    fontSize: 14,
  },
});
